apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: "plan-main-d9c5cc348e"
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
